// vim: ft=groovy
properties([
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '3', daysToKeepStr: '', numToKeepStr: '3')),
    pipelineTriggers([[$class: 'PeriodicFolderTrigger', interval: '2d']])
])

node('cloud') {
    stage('CLOUD: Host Debug Information') {
        sh 'set -x && hostname && uname -a && free -h && df -h'
    }
    deleteDir()
    dir('setup') {
        checkout scm
    }
    try {
        stage('CLOUD: Prepare factory') {
            sh "#!/bin/bash\npython3 <(curl -sL https://github.com/liquidinvestigations/factory/raw/master/install.py) factory"
        }
        stage('CLOUD: Build prerequisites image') {
            sh 'cp setup/jenkins-config.yml setup/ansible/vars/config.yml'
            sh 'mkdir images'
            sh 'factory/factory run --smp 2 --memory 2048 --share setup:/mnt/setup --share images:/mnt/images /mnt/setup/bin/jenkins_build /mnt/setup/bin/build_image cloud --tags prerequisites'
        }
        stage('CLOUD: Archive prerequisites image') {
            sh 'gzip -1 < images/ubuntu-x86_64-raw.img > liquid-cloud-x86_64-prerequisites.img.gz'
            archiveArtifacts 'liquid-cloud-x86_64-prerequisites.img.gz'
        }
    } finally {
        deleteDir()
    }
}

