# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by liquid initialization script
# Date: {timestamp}
*               @ALL          0
*               @user         8
