<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by liquid initialization script
 * Date: {timestamp}
 */
$conf['title'] = '{title}';
$conf['lang'] = 'en';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
