<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by liquid initialization script
 * Date: {timestamp}
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
