#!/bin/bash
set -e

cd /opt/hypothesis/h
source ../venv/bin/activate
source ../libexec/secrets.sh

export PYTHONPATH="${PWD}"
export DATABASE_URL="postgresql:///hypothesis"
export APP_URL="http://hypothesis.{{ liquid_domain }}"
export CLIENT_URL="http://client.hypothesis.{{ liquid_domain }}"
export ELASTICSEARCH_HOST="http://127.0.0.1:14312"

exec "$@"
