#!/usr/bin/env python3

import random
from pathlib import Path
from datetime import datetime
import subprocess
import json

TEMPLATE_DIR = '/opt/setup/ansible/roles/dokuwiki/files/dokuwiki-conf'

def get_timestamp():
    return '{} UTC'.format(datetime.utcnow())

def write(target, content):
    with target.open('w', encoding='utf8') as f:
        f.write(content)

def render(target, **extra):
    options = {'timestamp': get_timestamp()}
    options.update(extra)
    template_path = Path(TEMPLATE_DIR) / target.name
    if target.exists():
        print("skipping, already exists:", target)
    else:
        with template_path.open('r') as f:
            content = f.read().format(**options)
        print("writing:", target)
        write(target, content)


def random_salt():
    urandom = random.SystemRandom()
    return ''.join(urandom.choice('0123456789abcdef') for _ in range(128))


with open('/var/lib/liquid/conf/options.json', encoding='utf8') as f:
    liquid_options = json.load(f)

callback_url = (
    '{http_scheme}://dokuwiki.{domain}/doku.php'
    .format(**liquid_options)
)

keys_json = subprocess.check_output([
    'sudo', '-u', 'liquid-apps',
    '/opt/liquid-core/libexec/manage',
    'createoauth2app',
    'dokuwiki',
    callback_url,
])

oauth_keys = json.loads(keys_json.decode('utf8'))

oauth_url = '{scheme}://{domain}'.format(
    scheme='https' if liquid_options.get('use_https') else 'http',
    domain=liquid_options['domain'],
)

local_php_options = {
    'title': "wiki",
    'oauth_id': oauth_keys['client_id'],
    'oauth_secret': oauth_keys['client_secret'],
    'oauth_url': oauth_url,
}

data = Path('/opt/dokuwiki')

render(data / 'conf/acl.auth.php')
render(data / 'conf/local.php', **local_php_options)
render(data / 'conf/plugins.local.php')
render(data / 'conf/users.auth.php')
(data / 'conf/dokuwiki.php').unlink()
render(data / 'conf/dokuwiki.php')
write(data / 'data/meta/_htcookiesalt2', random_salt())

subprocess.check_call([
    'chown', '-R',
    'www-data:www-data',
    '/var/lib/liquid/dokuwiki/conf',
])
