#!/usr/bin/env python3

import random
from pathlib import Path
from datetime import datetime

TEMPLATE_DIR = '/opt/setup/ansible/roles/dokuwiki/files/dokuwiki-conf'

def get_timestamp():
    return '{} UTC'.format(datetime.utcnow())

def write(target, content):
    with target.open('w', encoding='utf8') as f:
        f.write(content)

def render(target, **extra):
    options = {'timestamp': get_timestamp()}
    options.update(extra)
    template_path = Path(TEMPLATE_DIR) / target.name
    if target.exists():
        print("skipping, already exists:", target)
    else:
        with template_path.open('r') as f:
            content = f.read().format(**options)
        print("writing:", target)
        write(target, content)


def random_salt():
    urandom = random.SystemRandom()
    return ''.join(urandom.choice('0123456789abcdef') for _ in range(128))

print("\n\n=== INITIALIZE DOKUWIKI ===\n")

data = Path('/opt/dokuwiki')

render(data / 'conf/acl.auth.php')
render(data / 'conf/local.php', title="wiki")
render(data / 'conf/plugins.local.php')
render(data / 'conf/users.auth.php')
(data / 'conf/dokuwiki.php').unlink()
render(data / 'conf/dokuwiki.php')
write(data / 'data/meta/_htcookiesalt2', random_salt())
