#!/usr/bin/env python3

import json
from pathlib import Path
import subprocess

KEYS_FILE = """\
export CLIENT_ID='{client_id}'
export CLIENT_SECRET='{client_secret}'
"""


def create_oauth2_app(app_name, redirect_uri):
    stdout = subprocess.check_output([
        '/opt/liquid-core/venv/bin/python',
        '/opt/liquid-core/liquid-core/manage.py',
        'createoauth2app',
        app_name,
        redirect_uri,
    ])
    return json.loads(stdout.decode('utf8'))


def write_oauth_keys(app_name, keys):
    keys_path = Path('/var/lib/liquid/oauth_keys') / app_name
    with keys_path.open('w', encoding='utf8') as keys_file:
        keys_file.write(KEYS_FILE.format(**keys))


def main():
    import sys
    args = sys.argv[1:]
    if len(args) != 2:
        print("Usage: create-oauth-application APP_NAME REDIRECT_URI")
        print(
            "The script will fill out keys under "
            "/var/lib/liquid/oauth_keys/$APP_NAME."
        )
        sys.exit(1)

    [app_name, redirect_uri] = args

    keys = create_oauth2_app(app_name, redirect_uri)
    write_oauth_keys(app_name, keys)


if __name__ == '__main__':
    main()
