#!/usr/bin/env python3

if __name__ == '__main__':
    from pathlib import Path
    import sys

    repo = Path(__file__).resolve().parent.parent
    sys.path.append(str(repo / 'py'))

    from liquid import lan
    lan.first_boot()
