#!/bin/bash
set -ex

cd /tmp

case "$1" in
    poweroff)
        nohup sh -c 'sleep 10 && poweroff' &> /dev/null &
        ;;
    reboot)
        nohup sh -c 'sleep 10 && reboot' &> /dev/null &
        ;;
    *)
        echo "$0: usage: $0 poweroff|reboot"
        exit 1
esac

