#!/usr/bin/env python3

if __name__ == '__main__':
    from pathlib import Path
    import sys

    repo = Path(__file__).resolve().parent.parent
    sys.path.append(str(repo / 'py'))

    from liquid.vpn import client
    [name] = sys.argv[1:]
    print(client.generate_config(name).strip())
