#!/bin/bash
set -e

if [ -f /var/lib/liquid/lan/eth0_no_dhcp ]; then
  echo "Skipping lan server (hotspot and eth0 dhcp)"
  exit 0
fi

(
  echo "Configuring lan"
  set -x
  /opt/liquid-core/libexec/manage putconfig lan '{"dhcp_range": "10.103.0.100,10.103.0.200,72h", "eth": true, "hotspot": {"ssid": "", "password": ""}, "ip": "10.103.0.1", "netmask": "255.255.255.0"}'
)
