#!/bin/bash
set -ex

echo 'liquid-admin:liquid' | chpasswd
echo 'devel: true' >> /opt/setup/ansible/vars/config.yml
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
