#!/bin/bash
set -e
printf '\n\n=== INITIALIZE MATRIX ===\n\n'
set -x

echo "Matrix just works, man. Let's just start it now..."
supervisorctl start matrix

function wait_url {
    X=0
    until $(curl --output /dev/null --silent --head --fail $1); do
        sleep 7
        ((X=X+1))
        if [[ $X -gt 20 ]]; then
            echo "wait_url: $1 timed out" >&2
            exit 1;
        fi
    done
}

wait_url 'http://127.0.0.1:55156'
